### ISSUE TITLE
PyPI dists contain stale modules

### ISSUE THREAD

**Issue by hoefling** [friendly-traceback/friendly-traceback#24]
To reproduce:
```sh
$ pip download friendly-traceback
$ unzip friendly_traceback-0.4.2-py3-none-any.whl
$ rsync -rv --ignore-existing --dry-run friendly_traceback/ /path/to/repo/friendly_traceback/
sending incremental file list
console.py
formatters.py
my_gettext.py

sent 1,325 bytes  received 30 bytes  2,710.00 bytes/sec
total size is 870,801  speedup is 642.66 (DRY RUN)
```
@aroberge I'm not sure what the cause is, most probably the `build` directory has to be removed from where you are building the dists. It will be recreated on the next build anyway. E.g. `python setup.py clean bdist_wheel` etc.

A modern and more reliable tool for projects that have switched to PEP 517-style layout is also [`build`](https://pypi.org/project/build/) that moves the building away from the repository, avoiding build files pollution:
```sh
$ pip install build
$ python -m build
```

Maybe it also makes sense to release from the CI, with jobs that trigger on new Git tags only. E.g. from a GH action, it could be something like
```yaml
name: ...
on: [push, pull_request]
jobs:
  ...
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Upload dist
        if: startsWith(github.ref, 'refs/tags/')  # <-- the 'release' job will trigger only on tags
        env:
          TWINE_NON_INTERACTIVE: true
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload dist/friendly_traceback-*{.whl,.tar.gz}
```
if you are using direct `setup.py` + `twine` invocation for producing dists.
